language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - |
    if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ] ; then
      pip install -q 'errbot<4.3'
    fi
  - |
    if [ "$TRAVIS_PYTHON_VERSION" = "3.5" ] ; then
      pip install -q 'errbot>=4.3'
    fi
  - |
    if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ] ; then
      pip install -q 'errbot>=4.3'
    fi
  - pip install -q pytest pytest-pep8 --use-wheel
  - pip install -q coverage coveralls --use-wheel
script:
  - coverage run --source pomodoro -m py.test --pep8
after_success:
  - coveralls
notifications:
  email: false
